#!/bin/bash

PASSWORD_KEY='<some-password-key>'

captured_password=$(osascript -s o -e 'set T to text returned of (display dialog "Enter password for '${PASSWORD_KEY}':" buttons {"Cancel", "OK"} default button "OK" default answer "" with hidden answer)')

if [ $? -eq 0 ] && [ -n "$captured_password" ]; then
    security delete-generic-password -a ${USER} -s ${PASSWORD_KEY} > /dev/null 2>&1
    security add-generic-password -a ${USER} -s ${PASSWORD_KEY} -w "$captured_password"
    echo 'Password saved successfully'
    exit 0
else
    echo 'Password capture failed; aborting'
    exit 1
fi

